### ISSUE TITLE
Storing ETM trace in persistent buffer.

### ISSUE THREAD

**Issue by HokageM** [ARM-software/CSAL#18]
I want to keep track of the last `N` instructions of the ETM and save them in a persistent buffer. This should be done during execution.

I found the `do_fetch_trace` function, which saves the traced data in a file. Is there also a way to save the traced data into another buffer? How do I need to configure the ETM for that purpose?

**Comment by HokageM** [comment]
This function should do what I ask for: `int cs_get_trace_data(cs_device_t dev, void *buf, unsigned int size)`

**Comment by algrant-arm** [comment]
I believe so. Note that the device here is the trace buffer (ETB) not the ETM. In the most general case, multiple trace sources (ETMs etc.) will funnel into a trace sink, and the data is collected from the sink, and it then needs to be demultiplexed to get each trace stream.

It can be set it up so that there's only one active trace source, and in that case you can even turn off the multiplex formatting in the ETB, but it's still the ETB where the trace ends up being collected from.

Alternatively if there's an ETR (trace router) on the trace path, it can write directly to a memory buffer.

**Comment by HokageM** [comment]
Thank you! I will try it out.
