### ISSUE TITLE
Support for Cortex-M33 which has ETMv4

### ISSUE THREAD

**Issue by seemakumar8** [ARM-software/CSAL#5]
Is it supported on Cortex-M based boards? I am particularly interested in M33 which has Coresight ETMv4 and ARMv8-M architecture.

Thanks

**Comment by algrant-arm** [comment]
Yes, it's supported on Cortex-M boards. The code is designed to be retargetable to RTOS or bare metal, and makes minimal demands on the OS. So you can run it on a Cortex-M board or on a Cortex-M management coprocessor on a larger system. In fact, in CSAL itself, there are no Arm dependencies, so you could even run CSAL on a non-Arm management coprocessor to manage a CoreSight subsystem around Arm-architecture mission CPUs. Or, you could run CSAL on an application CPU to manage the ETM in an on-chip Cortex-M. All that is required is that the CPU running CSAL has access to the target CPU ETM logic and other CoreSight components, somewhere in its memory map.

It should work, if there are any issues feel free to file a ticket. I realise it's two and a half years since you asked the question!
